apiVersion: v1
kind: Service
metadata:
  name: gender-classification-service
spec:
  type: NodePort
  selector:
    app: gender-classification
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
