apiVersion: v1
kind: Service
metadata:
  name: flight-price-api-service
spec:
  selector:
    app: flight-price-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
